server:
  port: 3344
spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri:            # GitHub上面的git仓库名字
        #### 搜索目录
          search-paths

